services:
  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html/nginx1:/usr/share/nginx/html:ro
      - ./logs/nginx1:/var/log/nginx
    networks:
      - proxy-network
    depends_on:
      - nginx2
    restart: unless-stopped

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8081:80"
    volumes:
      - ./configs/nginx2/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html/nginx2:/usr/share/nginx/html
      - ./temp/nginx2:/tmp/nginx_uploads
      - ./logs/nginx2:/var/log/nginx
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16